name: continue-on-error
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.ref }}    # Only one job per branch
      cancel-in-progress: true          # Cancel previous running job if new triggered
    steps:
      - run: echo "This is job1 for branch ${GITHUB_REF}"

  job2:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${{ github.ref }}   # Separate concurrency group
      cancel-in-progress: false         # Let multiple jobs run
    steps:
      - run: echo "This is job2 for branch ${GITHUB_REF}"
  optional-job:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: exit 1
   
