name: envs
on:
  workflow_dispatch:
env:
  filename: secrets
jobs:
  env-global:
     env:
       jobname: env-global 
     runs-on: ubuntu-latest
     steps:
       - name: step-level
         env:
           stepName: step-level     
         run: |
           echo "${{secrets.password}}"
           echo "${{vars.username}}"
           echo "${{env.filename}}"
           echo  "${{env.jobname}}"
           echo "${{env.stepName}}"       
      
