name: envs
on:
  workflow_dispatch:
env:
  filename: secrets
jobs:
  env-global:
     env:
       jobname: env-global 
     runs-on: ubuntu-latest
     steps:
       - run: echo "${{secrets.password}}"
       - run: echo "${{vars.username}}"
       - run: echo "${{env.filename}}"
       - run: echo  "${{env.jobname}}"
       
      
