name: branch
on:
  workflow_dispatch:
jobs:
  main_branch: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - run: ls -ltr
  hero_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: hero 
      - run: ls -ltr     
